import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { test, expect, type Page } from '@playwright/test'
const require=createRequire(import.meta.url)
const {PrismaClient}=require('../../server/node_modules/@prisma/client')
const db=new PrismaClient(),out='/tmp/cps-role-ui-audit/round2'
async function read<T>(page:Page,path:string):Promise<T>{return page.evaluate(async p=>{const m='/src/lib/http.ts';const{http}=await import(/* @vite-ignore */m);return http.get(p)},path)}
async function login(page:Page,account:string){await page.goto(account==='admin'?'/#/login':'/#/portal/login');await page.locator('input').first().fill(account);await page.locator('input[type=password]').fill('demo');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page).not.toHaveURL(/\/login$/)}
test.beforeEach(async({context})=>{mkdirSync(out,{recursive:true});await context.route('**/*',route=>{const u=new URL(route.request().url());return ['localhost','127.0.0.1'].includes(u.hostname)||['data:','blob:'].includes(u.protocol)?route.continue():route.abort()})})
test.afterAll(async()=>{await db.$disconnect()})
for(const account of ['admin','brand','agent'])test(`R2 ${account} accepted lost acknowledgment reload recovers exact operation without another generation`,async({page})=>{
 await page.setViewportSize({width:account==='admin'?1440:account==='brand'?390:820,height:900});await page.emulateMedia({colorScheme:account==='agent'?'dark':'light',reducedMotion:account==='brand'?'reduce':'no-preference'});await login(page,account);await page.goto(account==='admin'?'/#/aigc':`/#/portal/${account}/aigc`);if(account==='admin')await page.getByRole('button',{name:'生成素材',exact:true}).click()
 const form=account==='admin'?page.getByRole('dialog'):page.locator('main');await expect(form.locator('select').first().locator('option[value=social_pack]')).toHaveCount(1);await form.locator('select').first().selectOption('social_pack');await form.locator('select').nth(1).selectOption('retain');await form.locator('select').nth(2).selectOption('cheap');const brief=`虚构青禾${account}会员，每月三本科普书摘要，年费99元。已订阅客户根据实际阅读需求自主续费。`;await form.locator('textarea').fill(brief)
 const before=await read<{credits:{balance:number}}>(page,'/aigc/billing/credits');let accepted:{job:{id:string}}|undefined;let key='',posts=0
 await page.route('**/aigc/factory/generate',async route=>{posts++;key=route.request().headers()['idempotency-key'];const response=await route.fetch();accepted=await response.json();await route.abort('failed')})
 await form.getByRole('button',{name:'生成',exact:true}).click();await expect.poll(()=>accepted?.job?.id).toBeTruthy();await expect(page.getByText('提交结果尚未确认，请在待确认请求中查询原任务，或保留相同内容后重试。关闭页面不代表取消生成。',{exact:true})).toBeVisible();await page.screenshot({path:`${out}/${account}-lost-ack.png`,fullPage:true});await page.reload();await expect(page.getByRole('region',{name:'待确认生成请求'})).toBeVisible();const result=page.waitForResponse(r=>r.url().includes(`/operations/${key}`));await page.getByRole('button',{name:'查询原任务',exact:true}).click();expect((await result).status()).toBe(200);await expect(page.locator('article').filter({hasText:accepted!.job.id})).toBeVisible();expect(posts).toBe(1)
 const after=await read<{credits:{balance:number;reservedCredits:number;recentLedger:Array<{job_id:string;amount:number}>};usage:Array<{job_id:string}>}>(page,'/aigc/billing/credits');expect(before.credits.balance-after.credits.balance).toBe(4);expect(after.credits.reservedCredits).toBe(0);expect(after.usage.filter(e=>e.job_id===accepted!.job.id)).toHaveLength(1);expect(after.credits.recentLedger.filter(e=>e.job_id===accepted!.job.id&&e.amount<0)).toHaveLength(1);expect(await db.asset.count({where:{jobId:accepted!.job.id}})).toBe(account==='admin'?0:1)
 const article=page.locator('article').filter({hasText:accepted!.job.id});await article.getByText('查看素材',{exact:true}).click();await expect(article).toContainText('年费99元');await expect(article).not.toContainText('先分任务再选工具');await page.screenshot({path:`${out}/${account}-recovered-original.png`,fullPage:true});writeFileSync(`${out}/${account}-recovery.json`,JSON.stringify({key,job:accepted!.job.id,posts,actualDebit:4,usage:1,assetRows:account==='admin'?0:1},null,2))
})
test('R2 brand product accepted response loss survives reload and replays one creation',async({page})=>{
 await login(page,'brand');await page.goto('/#/portal/brand/products');await page.getByRole('button',{name:'上架商品',exact:true}).click();const name=`虚构青禾R2恢复商品${Date.now()}`;await page.getByPlaceholder('如：会员 VIP 连续包月').fill(name);let writes=0;const keys:string[]=[];let accepted:{id:string}|undefined
 await page.route('**/portal/brand/products',async route=>{if(route.request().method()!=='POST')return route.continue();writes++;keys.push(route.request().headers()['idempotency-key']);const response=await route.fetch();accepted=await response.json();if(writes===1)return route.abort('failed');return route.fulfill({response})})
 await page.getByRole('button',{name:'创建草稿',exact:true}).click();await expect.poll(()=>accepted?.id).toBeTruthy();await page.reload();await expect(page.getByText('待确认的商品创建',{exact:true})).toBeVisible();await page.getByRole('button',{name:'找回原商品',exact:true}).click();await expect(page.getByText('待确认的商品创建',{exact:true})).toHaveCount(0);expect(writes).toBe(2);expect(keys[0]).toBeTruthy();expect(keys[1]).toBe(keys[0]);expect(await db.product.count({where:{brandId:'youdao',name}})).toBe(1);expect(await db.auditLog.count({where:{action:'product.create',resourceId:accepted!.id}})).toBe(1);await page.screenshot({path:`${out}/brand-product-recovered.png`,fullPage:true})
})
test('R2 concrete membership carousel retrieves and downloads all six exact pages with keyboard actions',async({page})=>{
 test.setTimeout(150000);await login(page,'brand');const response=await page.evaluate(async()=>{const m='/src/lib/aigcApi.ts';const{aigcApi}=await import(/* @vite-ignore */m);return aigcApi.generate({assetType:'carousel',platform:'xhs',intent:'retain',prompt:'虚构青禾读书会员，每月三本科普书摘要，年费99元。面向已订阅客户，自主决定是否续费，不承诺额外优惠。',modelPreset:'cheap'})});expect(response.job?.status).toBe('completed');const files:string[]=response.result.assets.files;expect(files).toHaveLength(6)
 await page.goto('/#/portal/brand/aigc');const article=page.locator('article').filter({hasText:response.job.id});await expect(article).toBeVisible();const details=article.getByText('查看素材',{exact:true});await details.focus();await page.keyboard.press('Enter');const readbacks=[]
 for(let index=0;index<6;index++){
  const button=article.getByRole('button',{name:`查看图片 ${index+1}`,exact:true});await button.focus();await page.keyboard.press('Enter');const img=article.getByRole('img',{name:`生成图片 ${index+1}`,exact:true});await expect.poll(()=>img.evaluate((n:HTMLImageElement)=>n.naturalWidth)).toBeGreaterThan(0);const bytes=await img.evaluate(async(n:HTMLImageElement)=>Array.from(new Uint8Array(await(await fetch(n.src)).arrayBuffer())));expect(Buffer.from(bytes).equals(readFileSync(files[index]))).toBe(true);const downloaded=page.waitForEvent('download');await article.getByRole('link',{name:`下载图片 ${index+1}`,exact:true}).click();const saved=await downloaded;expect(readFileSync((await saved.path())!).equals(readFileSync(files[index]))).toBe(true);await saved.saveAs(`${out}/downloaded-carousel-page-${index+1}.png`);expect(readFileSync(`${out}/downloaded-carousel-page-${index+1}.png`).equals(readFileSync(files[index]))).toBe(true);await img.screenshot({path:`${out}/concrete-carousel-page-${index+1}.png`});readbacks.push({index,bytes:bytes.length,exactBlob:true,exactDownload:true})
 }
 await page.reload();await expect(page.locator('article').filter({hasText:response.job.id})).toBeVisible();writeFileSync(`${out}/six-page-readback.json`,JSON.stringify({job:response.job.id,pages:readbacks},null,2))
})
