import { afterEach, describe, expect, it, vi } from 'vitest'

afterEach(()=>{vi.unstubAllGlobals();vi.resetModules()})
describe('real API refresh boundaries',()=>{
  it('a different account in the shared refresh cookie never receives a replayed mutation',async()=>{
    const {api,setAccessToken,onAuthLost}=await import('./http')
    setAccessToken('brand-a-access','brand-a')
    const lost=vi.fn();onAuthLost(lost)
    const fetch=vi.fn().mockResolvedValueOnce(new Response('{}',{status:401}))
      .mockResolvedValueOnce(Response.json({access:'brand-b-access',user:{id:'brand-b'}}))
      .mockResolvedValue(Response.json({ok:true}))
    vi.stubGlobal('fetch',fetch)
    await expect(api('/portal/brand/products',{method:'POST',body:'{}'})).rejects.toMatchObject({status:401})
    expect(fetch).toHaveBeenCalledTimes(2)
    expect(lost).toHaveBeenCalledOnce()
  })
  it('same-account refresh rotates credentials and replays once',async()=>{
    const {api,setAccessToken}=await import('./http')
    setAccessToken('old','brand-a')
    const fetch=vi.fn().mockResolvedValueOnce(new Response('{}',{status:401}))
      .mockResolvedValueOnce(Response.json({access:'new',user:{id:'brand-a'}}))
      .mockResolvedValueOnce(Response.json({ok:true}))
    vi.stubGlobal('fetch',fetch)
    await expect(api('/portal/summary')).resolves.toEqual({ok:true})
    expect(fetch.mock.calls[2][1].headers.Authorization).toBe('Bearer new')
  })
  it('late successful old-account body is discarded after logout/new login',async()=>{
    const {api,setAccessToken}=await import('./http')
    setAccessToken('old-account')
    let release!:(value:unknown)=>void
    let entered!:()=>void;const started=new Promise<void>(r=>{entered=r})
    vi.stubGlobal('fetch',vi.fn(async()=>({ok:true,status:200,json:()=>{entered();return new Promise(r=>{release=r})}})))
    const request=api('/projects');await started;setAccessToken(null);setAccessToken('new-account');release({private:'old fixture'})
    await expect(request).rejects.toMatchObject({status:401})
  })
  it('account switch during refresh completion never replays a mutation',async()=>{
    const {api,setAccessToken}=await import('./http')
    setAccessToken('old-account')
    const fetch=vi.fn().mockResolvedValueOnce(new Response('{}',{status:401})).mockImplementationOnce(async()=>({ok:true,status:200,json:async()=>{
      queueMicrotask(()=>setAccessToken('new-account'))
      return {access:'old-refreshed'}
    }}))
    vi.stubGlobal('fetch',fetch)
    await expect(api('/orders',{method:'POST',body:'{}'})).rejects.toMatchObject({status:401})
    expect(fetch).toHaveBeenCalledTimes(2)
  })
  it('transient refresh outage does not log out a valid session',async()=>{
    const {api,setAccessToken,onAuthLost}=await import('./http')
    setAccessToken('original');const lost=vi.fn();onAuthLost(lost)
    const fetch=vi.fn().mockResolvedValueOnce(new Response('{}',{status:401})).mockResolvedValueOnce(new Response('{}',{status:503}))
    vi.stubGlobal('fetch',fetch)
    await expect(api('/projects')).rejects.toMatchObject({status:401})
    expect(lost).not.toHaveBeenCalled()
  })
  it('actual refresh rejection ends unchanged session',async()=>{
    const {api,setAccessToken,onAuthLost}=await import('./http')
    setAccessToken('original');const lost=vi.fn();onAuthLost(lost)
    vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response('{}',{status:401})).mockResolvedValueOnce(new Response('{}',{status:401})))
    await expect(api('/projects')).rejects.toMatchObject({status:401})
    expect(lost).toHaveBeenCalledOnce()
  })
  it('late refresh cannot resurrect logout or replace a newer login',async()=>{
    const {api,setAccessToken,onAuthLost}=await import('./http')
    const lost=vi.fn();onAuthLost(lost);setAccessToken('old')
    let release!:()=>void
    const waiting=new Promise<void>(r=>{release=r})
    let entered!:()=>void;const started=new Promise<void>(r=>{entered=r})
    const fetch=vi.fn().mockResolvedValueOnce(new Response('{}',{status:401})).mockImplementationOnce(async()=>{entered();await waiting;return Response.json({access:'stale'})}).mockResolvedValue(Response.json({ok:true}))
    vi.stubGlobal('fetch',fetch)
    const request=api('/projects');await started;setAccessToken(null);setAccessToken('new-login');release()
    await expect(request).rejects.toMatchObject({status:401})
    await api('/next')
    expect(fetch.mock.calls[2][1].headers.Authorization).toBe('Bearer new-login')
    expect(lost).not.toHaveBeenCalled()
  })
})
