import { beforeEach, expect, it, vi } from 'vitest'
import { PortalController } from './portal.controller'
const user={id:'synthetic-user',name:'Synthetic author',roleId:'brand',scopeType:'brand',scopeId:'synthetic-brand',perms:[]} as const
const body={name:'Synthetic subscription',firstPrice:99,renewPrice:99}
let record:any,prisma:any,audit:any,controller:PortalController
beforeEach(()=>{record=null;prisma={product:{findUnique:vi.fn(async()=>record),create:vi.fn(async({data}:any)=>{record={...data,deletedAt:null};return record})}};audit={record:vi.fn().mockResolvedValue(undefined)};controller=new PortalController(prisma,audit)})
it('atomic create stores durable identity and normalized fingerprint, replay does not recreate or audit twice',async()=>{
 const a=await controller.addBrandProduct(body,user as never,'operation-1');const b=await controller.addBrandProduct({...body,category:'',description:'',billingCycle:'continuous',defaultSharePct:30,bundleEligible:true,exclusiveGroup:'',tags:[]},user as never,'operation-1')
 expect(b).toEqual(a);expect(record.creationKey).toMatch(/^[a-f0-9]{64}$/);expect(record.creationFingerprint).toMatch(/^[a-f0-9]{64}$/);expect(record.firstPrice).toBe(9900);expect(prisma.product.create).toHaveBeenCalledOnce();expect(audit.record).toHaveBeenCalledOnce()
})
it('same operation changed payload conflicts and leaves the first product intact',async()=>{await controller.addBrandProduct(body,user as never,'operation-1');await expect(controller.addBrandProduct({...body,name:'Different intent'},user as never,'operation-1')).rejects.toThrow('不同商品内容');expect(record.name).toBe(body.name)})
it('replay after ordinary edit returns the original id without overwriting the edit; deleted originals cannot be recreated',async()=>{const made=await controller.addBrandProduct(body,user as never,'operation-1');record.name='Legitimate later edit';expect(await controller.addBrandProduct(body,user as never,'operation-1')).toEqual(made);expect(record.name).toBe('Legitimate later edit');record.deletedAt=new Date();await expect(controller.addBrandProduct(body,user as never,'operation-1')).rejects.toThrow('已删除');expect(prisma.product.create).toHaveBeenCalledOnce()})
it('a unique violation unrelated to creationKey is not falsely replayed',async()=>{const collision={code:'P2002'};prisma.product.create.mockRejectedValue(collision);await expect(controller.addBrandProduct(body,user as never,'operation-1')).rejects.toBe(collision);expect(audit.record).not.toHaveBeenCalled()})
it('a competing committed identity is replayed only when its fingerprint matches',async()=>{await controller.addBrandProduct(body,user as never,'operation-1');const committed=record;record=null;prisma.product.findUnique.mockResolvedValueOnce(null).mockResolvedValueOnce(committed);prisma.product.create.mockRejectedValueOnce({code:'P2002'});expect(await controller.addBrandProduct(body,user as never,'operation-1')).toEqual({ok:true,id:committed.id});expect(audit.record).toHaveBeenCalledOnce()})
it('legacy no-key operations remain independent and do not retain a creation identity',async()=>{const a=await controller.addBrandProduct(body,user as never);const b=await controller.addBrandProduct(body,user as never);expect(a.id).not.toBe(b.id);expect(record.creationKey).toBeNull();expect(record.creationFingerprint).toBeNull();expect(audit.record).toHaveBeenCalledTimes(2)})
